
binary := 'monitoror'

download_linux_x64:
  curl -sL -o {{binary}} $(curl -s https://api.github.com/repos/monitoror/monitoror/releases/latest | grep 'browser_download_url.*monitoror-linux-amd64' | cut -d: -f2,3 | tr -d \")
  chmod +x {{binary}}

download_macos:
  curl -sL -o {{binary}} $(curl -s https://api.github.com/repos/monitoror/monitoror/releases/latest | grep 'browser_download_url.*monitoror-macos' | cut -d: -f2,3 | tr -d \")
  chmod +x {{binary}}
